### ISSUE TITLE
Blinking 1px line above the sticky header

### ISSUE THREAD

**Issue by tomasbaran** [fluttercommunity/flutter_sticky_headers#35]
First off, huge thanks for this plugin. Big big help!

Tiny bug: When scrolling there is a 1px line above the header. See here: https://share.icloud.com/photos/00iofG5V2K9aKDL6Mb2gZ8uKg 

demostration: https://share.icloud.com/photos/0O38S_lN4_3i1TAmXjyu22QiQ 

Here is the code:
```
Expanded(
                child: ListView.builder(
                  itemCount: 1,
                  itemBuilder: (BuildContext context, int index) {
                    return Column(
                      children: <Widget>[
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.stretch,
                          children: <Widget>[
                            ByCategory(category: 'WORLD'),
                            SizedBox(
                              height: grid1,
                            ),
                            WorldRow1(),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceAround,
                              children: <Widget>[
                                WorldRow3(
                                  statusColor: themeOrange,
                                  title: 'ACTIVE',
                                ),
                                SizedBox(
                                  width: grid2,
                                ),
                                WorldRow3(
                                  statusColor: themeRed,
                                  title: 'DIED',
                                ),
                                SizedBox(
                                  width: grid2,
                                ),
                                WorldRow3(
                                  statusColor: themeGreen,
                                  title: 'RECOVERED',
                                ),
                              ],
                            ),
                          ],
                        ),
                        Padding(
                          padding: const EdgeInsets.only(top: grid7),
                          child: StickyHeader(
                            header: Container(
                              padding: EdgeInsets.only(top: 88.0),
                              decoration: BoxDecoration(
                                color: themeBackgroundColor,
                                borderRadius: BorderRadius.only(
                                  bottomLeft: Radius.circular(grid2),
                                  bottomRight: Radius.circular(grid2),
                                ),
                              ),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.stretch,
                                children: <Widget>[
                                  ByCategory(category: 'BY COUNTRY'),
                                  SizedBox(
                                    height: grid1,
                                  ),
                                  CountriesTableHeader(),
                                ],
                              ),
                            ),
                            content: Column(
                              children: <Widget>[
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                                CountryRow(),
                              ],
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              ),
```

**Comment by britannio** [comment]
I'm facing this issue too

**Comment by daveleenew** [comment]
I'm facing this issue too

**Comment by zhanghuibiao** [comment]
我也遇到这个问题

**Comment by chiragmittal19** [comment]
@tomasbaran did you find any solution to that?

**Comment by tomasbaran** [comment]
@chiragmittal19 Unfortunately I did not.

**Comment by while-loop** [comment]
Are any of you guys not using an AppBar? Or if you are, is your elevation 0?

Based on https://github.com/fluttercommunity/flutter_sticky_headers/pull/28, I have a feeling the code isn't taking non-default elevations into account. 

I did use that PR in my code, but quickly found a bug that wasn't keeping headers stickied. I realized that the v0.1.8+1 released on flutter pub.dev packages isn't even the same code as this repository. 

So I downloaded the tar from pub.dev and patched #28's PR and it seems to be working now with some modifications on my end too.


old code:
```dart
return body;
```

new code:
```dart
var theme = Theme.of(context);
return Theme(
    data: theme.copyWith(appBarTheme: theme.appBarTheme.copyWith(elevation: 4)),
    child: body,
);
```

pubspec:
```yaml
dependencies:
  ...
  sticky_headers:
    git:
      url: https://github.com/while-loop/flutter_sticky_headers.git
      ref: "ac28980d81b8adf8a3bd14a875abedea5e89ea3f"
```

**Comment by haydgately** [comment]
@while-loop Where are you placing this new code? I am facing this issue sadly. Thanks in advance for any help

**Comment by haydgately** [comment]
@while-loop I found it but your fix presents the error 

The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()

`The relevant error-causing widget was: 
  StickyHeader file:///Users/haydgately/Documents/GitHub/project/lib/screens/tables/tables_screen.dart:132:44
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      double.- (dart:core-patch/double.dart:33:23)
#2      RenderStickyHeader.paint (package:sticky_headers/sticky_headers/render.dart:192:55)
#3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
#4      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
...
The following RenderObject was being processed when the exception was fired: RenderStickyHeader#16d7f relayoutBoundary=up6
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=359.0, 0.0<=h<=Infinity)
...  layer: OffsetLayer#d5a2e
...    engine layer: OffsetEngineLayer#ecfbf
...    offset: Offset(0.0, 0.0)
...  size: Size(359.0, 1009.0)
RenderObject: RenderStickyHeader#16d7f relayoutBoundary=up6
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=359.0, 0.0<=h<=Infinity)
  layer: OffsetLayer#d5a2e
    engine layer: OffsetEngineLayer#ecfbf
    offset: Offset(0.0, 0.0)
  size: Size(359.0, 1009.0)
...  child 1: RenderFlex#f65f9 relayoutBoundary=up7 NEEDS-PAINT
...    parentData: offset=Offset(0.0, 49.0); id=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...    size: Size(359.0, 960.0)
...    direction: vertical
...    mainAxisAlignment: start
...    mainAxisSize: max
...    crossAxisAlignment: center
...    verticalDirection: down
...    child 1: RenderPadding#58f4a relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#5f5a3 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#aa783 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#47aad relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 2: RenderPadding#8da02 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 40.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#c16b5 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#9c91e relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#ab4b9 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 3: RenderPadding#bb89b relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 80.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#206b4 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#a2f04 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#2129f relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 4: RenderPadding#f15dc relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 120.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#6d3ae relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#f812d relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#646b9 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 5: RenderPadding#96888 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 160.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#9f5d0 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#249c0 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#7481d relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 6: RenderPadding#39d02 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 200.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#25334 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#64967 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#98c30 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 7: RenderPadding#da5e6 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 240.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#9573c relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#636b7 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#768bd relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 8: RenderPadding#68b94 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 280.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#f630d relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#98ed5 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#23016 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 9: RenderPadding#ecd5a relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 320.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#0ebc4 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#6522e relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#97a14 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 10: RenderPadding#34c97 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 360.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#3303b relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#d0873 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#d57ed relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 11: RenderPadding#bd580 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 400.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#2036c relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#2b6f4 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#0c185 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 12: RenderPadding#bbc72 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 440.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#6f372 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#92150 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#7d481 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 13: RenderPadding#a64f8 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 480.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#00adc relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#b4ce4 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#566ef relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 14: RenderPadding#04cdc relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 520.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#cd091 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#2975e relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#33ab8 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 15: RenderPadding#68202 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 560.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#77425 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#eb6f8 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#beac1 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 16: RenderPadding#210fc relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 600.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#14dd9 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#cc612 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#c75e6 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 17: RenderPadding#17e07 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 640.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#963c6 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#16b22 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#8eb82 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 18: RenderPadding#fb0da relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 680.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#3a556 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#0ed02 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#ed19c relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 19: RenderPadding#1e395 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 720.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#6fe33 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#cf4d0 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#57df3 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 20: RenderPadding#068a3 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 760.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#106da relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#909a3 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#ba10d relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 21: RenderPadding#c2fdb relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 800.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#7ff90 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#313a9 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#90a01 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 22: RenderPadding#9a4cc relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 840.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#d69e3 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#80818 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#e0e6e relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 23: RenderPadding#9ae01 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 880.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#0ae61 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#89030 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#53591 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...    child 24: RenderPadding#43b0d relayoutBoundary=up8 NEEDS-PAINT
...      parentData: offset=Offset(0.0, 920.0); flex=null; fit=null (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 40.0)
...      padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...      textDirection: ltr
...      child: RenderFlex#8f751 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: offset=Offset(0.0, 8.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 32.0)
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderFlex#8384d relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 24.0)
...          direction: horizontal
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          textDirection: ltr
...          verticalDirection: down
...        child 2: RenderPadding#dd335 relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 24.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 8.0)
...          padding: EdgeInsets(0.0, 8.0, 0.0, 0.0)
...          textDirection: ltr
...  child 2: _RenderColoredBox#3bed7 relayoutBoundary=up7 NEEDS-PAINT
...    parentData: offset=Offset(0.0, 228.4); id=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...    size: Size(359.0, 49.0)
...    behavior: opaque
...    child: RenderClipRRect#9ef53 relayoutBoundary=up8 NEEDS-PAINT
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...      size: Size(359.0, 49.0)
...      child: RenderPadding#eef96 relayoutBoundary=up9 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...        size: Size(359.0, 49.0)
...        padding: EdgeInsets(0.0, 16.0, 0.0, 16.0)
...        textDirection: ltr
...        child: _RenderColoredBox#e0c1a relayoutBoundary=up10 NEEDS-PAINT
...          parentData: offset=Offset(0.0, 16.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=359.0, 0.0<=h<=Infinity)
...          size: Size(359.0, 17.0)
...          behavior: opaque`

**Comment by Cosminnv** [comment]
any solution for this?

**Comment by haydgately** [comment]
I abandoned using the whole thing I'm afraid!

**Comment by Cosminnv** [comment]
> I abandoned using the whole thing I'm afraid!

I actually managed to solve it thanks to @while-loop. The only problem i had was that his fork wasn't null safety so i added that myself based on the last commit on the original repository. [Here's the link if anyone wants to try it](https://github.com/Cosminnv/flutter_sticky_headers)

In my case i had no AppBar so what i did was add in the scaffold where i have the list
`Scaffold(body:...)`

the following elevation as @while-loop suggested

`Scaffold(
      body: Theme(
        data: theme.copyWith(
            appBarTheme: theme.appBarTheme.copyWith(elevation: 4)),
        child:...`

,with the dependency in pubspec.yaml pointing to my fork like this:
`dependencies:
 [...]
  sticky_headers:
    git:
     url: https://github.com/Cosminnv/flutter_sticky_headers.git
     ref: ddecfaf85a7fb3bb0838e60a8644730d0db955fe`

Now it seems to be working all right.

**Comment by Mhamza-MM** [comment]
Another workaround is to wrap the header in the Container widget and set the border matching the color of the header.

  header: Container(
        decoration: BoxDecoration(
          **color: Colors.white,**
          border: Border.all(
            **color: Colors.white,**
          ),
        ),
        child: ........
      ),

**Comment by Mhamza-MM** [comment]
Another workaround is to wrap the header in the Container widget and set the border color matching the color of the header.
```

header: Container(
  decoration: BoxDecoration(
    color: Colors.white,
    border: Border.all(
    color: Colors.white,
    ),
  ),
  child: ........
),

```

**Comment by slightfoot** [comment]
Fixed as-of v0.3.0.

**Comment by dehypnosis** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/3263661/169384014-01475840-c494-4f88-8548-3523125fa3d9.png">

@slightfoot  Sorry but seems still happening..

flutter 3.0.0
sticky_headers: ^0.3.0+2

**Comment by dehypnosis** [comment]
<img width="943" alt="image" src="https://user-images.githubusercontent.com/3263661/169387992-2fc3d3eb-ac53-4ae8-aee5-dfb6e6aa06d2.png">

I made a PR to make it fixed.
Just changed 'round' logics to 'ceil' for conservative pixel calculation.
Then it worked in iOS, Web without blinking line.

https://github.com/fluttercommunity/flutter_sticky_headers/pull/63

**Comment by zhushenwudi** [comment]
@slightfoot    Still exist on iPhone XR

**Comment by while-loop** [comment]
> Another workaround is to wrap the header in the Container widget and set the border color matching the color of the header.

This worked for me after one addition (`v0.3.0+2`): 
```diff
header: Container(
  decoration: BoxDecoration(
    color: Colors.white,
    border: Border.all(
    color: Colors.white,
+   strokeAlign: BorderSide.strokeAlignOutside
    ),
  ),
  child: ........
),
```

**Comment by zhushenwudi** [comment]
> > Another workaround is to wrap the header in the Container widget and set the border color matching the color of the header.
> 
> This worked for me after one addition (`v0.3.0+2`):
> 
> ```diff
> header: Container(
>   decoration: BoxDecoration(
>     color: Colors.white,
>     border: Border.all(
>     color: Colors.white,
> +   strokeAlign: BorderSide.strokeAlignOutside
>     ),
>   ),
>   child: ........
> ),
> ```

great，it also work for me!
